version: '3'
services:
  web:
    build: .
    container_name: lb5001
    links:
      - db
    depends_on:
      - db
    ports:
     - "5001:5001"
  db:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - d:/Software Architecture CS654A/DatabaseVolume:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb